@startuml
scale 2
skinparam monochrome true
skinparam shadowing false
left to right direction
skinparam actorStyle stick
skinparam defaultFontSize 20

actor "User" as User

rectangle "Usecase - Diagram" {
  rectangle "Features" {
    usecase "Data Sensor" as UC_Sensor
    usecase "Monitor" as UC_Monitor
    usecase "Add Kit" as UC_AddKit
    usecase "Actuator Control" as UC_Control
    usecase "Notification" as UC_Notify
    usecase "History" as UC_History
    usecase "Settings" as UC_Settings
    usecase "Profile" as UC_Profile
  }
  
  rectangle "Auth" {
    usecase "Login" as UC_Login
    usecase "Register" as UC_Register
    usecase "Logout" as UC_Logout
  }
}

User --> UC_Sensor
User --> UC_Monitor
User --> UC_AddKit
User --> UC_Control
User --> UC_Notify
User --> UC_History
User --> UC_Settings
User --> UC_Profile
User --> UC_Login
User --> UC_Register
User --> UC_Logout

UC_Sensor ..> UC_Login : include
UC_Monitor ..> UC_Login : include
UC_AddKit ..> UC_Login : include
UC_Control ..> UC_Login : include
UC_Notify ..> UC_Login : include
UC_History ..> UC_Login : include
UC_Settings ..> UC_Login : include
UC_Profile ..> UC_Login : include

@enduml
