@startuml
title Sequence Diagram - Login

actor "User" as User
participant "Login Screen" as Form
participant "AuthService" as Auth
participant "Firebase Auth" as Firebase
participant "Home Screen" as Home

' === Awal ===
User -> Form : Membuka aplikasi
activate Form
Form -> User : Menampilkan form login
deactivate Form

' === Proses input ===
User -> Form : Input email dan password
activate Form
Form -> User : Menampilkan inputan di form
deactivate Form

User -> Form : Klik tombol Login
activate Form

' === Kirim ke AuthService ===
Form -> Auth : signInWithEmailPassword(email, password)
activate Auth

' === Validasi ke Firebase ===
Auth -> Firebase : signInWithEmailAndPassword()
activate Firebase
Firebase -> Firebase : Validasi kredensial
Firebase --> Auth : UserCredential / Error
deactivate Firebase

' === Handling hasil ===
alt Login berhasil
  Auth --> Form : Return UserCredential
  Form -> Home : Navigate ke Home Screen
  activate Home
  Home -> User : Menampilkan halaman utama
  deactivate Home
else Login gagal
  Auth --> Form : Throw FirebaseAuthException
  Form -> User : Menampilkan pesan error
end

deactivate Auth
deactivate Form

@enduml
